import house01 from '../img/house01.jpg';
import house02 from '../img/house02.jpg';
import house03 from '../img/house03.jpg';
import house04 from '../img/house04.jpg';
import office01 from '../img/office01.jpg';
import office02 from '../img/office02.jpg';
import office03 from '../img/office03.jpg';

const properties = () => {
  return [
    {
      id: '1',
      title: 'Palm Harbor',
      price: 2095,
      img: house01,
      location: '2699 Green Valley, Highland Lake, FL, USA',
      popular: true,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 2,
        area: '5x7',
      },
    },

    {
      id: '2',
      title: 'Beverly Springfield',
      price: 2700,
      img: house02,
      location: '2821 Lake Sevilla, Palm Harbor, TX, USA',
      popular: true,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 2,
        area: '6x7.5',
      },
    },

    {
      id: '3',
      title: 'Faulkner Ave',
      price: 4550,
      img: house03,
      location: '909 Woodland St, Michigan, IN, USA',
      popular: true,
      date: '2022-01-10',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 3,
        area: '8x10',
      },
    },

    {
      id: '4',
      title: 'Eliason Ave',
      price: 3550,
      img: house04,
      location: 'Springville, California, USA',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 3,
        area: '7x15',
      },
    },

    {
      id: '5',
      title: 'Dan Gold',
      price: 4550,
      location: 'Lima, Peru',
      popular: false,
      img: office01,
      date: '2022-01-10',
      propertyType: {
        name: 'Workspace',
        rooms: 2,
        bathrooms: 2,
        area: '8x11',
      },
    },
    {
      id: '6',
      title: 'Nastuh Ave',
      price: 3550,
      img: office02,
      location: 'Club Workspace Clerkenwell Workshops, Farringdon, London, UK',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 3,
        area: '9x15',
      },
    },
    {
      id: '7',
      title: 'Acea View',
      price: 4550,
      img: office01,
      location: 'Timișoara, Romania',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 2,
        area: '8x13',
      },
    },

    {
      id: '8',
      title: 'Nastuh Abootalebi',
      price: 4550,
      img: office01,
      location: 'California, USA',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'Workspace',
        rooms: 2,
        bathrooms: 2,
        area: '9x18',
      },
    },

    {
      id: '9',
      title: 'Bench Accounting',
      price: 4550,
      img: office03,
      location: 'Sunday Digital, Munich, Germany',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'Workspace',
        rooms: 2,
        bathrooms: 2,
        area: '9x15',
      },
    },

    {
      id: '10',
      title: 'Go to Phil Hearing',
      price: 3050,
      img: house02,
      location: 'Yellow Springs, OH, USA',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'House',
        rooms: 2,
        bathrooms: 2,
        area: '9x18',
      },
    },

    {
      id: '11',
      title: 'Bechert Avenue',
      price: 4200,
      img: house04,
      location: 'CA, USA',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 3,
        area: '9x16',
      },
    },

    {
      id: '12',
      title: 'Gades',
      price: 4200,
      img: office03,
      location: 'Romania',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'Workspace',
        rooms: 4,
        bathrooms: 3,
        area: '9x12',
      },
    },

    {
      id: '13',
      title: 'Kara Eads',
      price: 4200,
      img: house02,
      location: 'Peru',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 2,
        area: '9x14',
      },
    },

    {
      id: '14',
      title: 'Kara Eads',
      price: 3000,
      img: office01,
      location: 'Las Vegas, USA',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 2,
        area: '9x14',
      },
    },

    {
      id: '15',
      title: 'Ksenia Balandina',
      price: 3000,
      img: house02,
      location: 'Las Vegas, USA',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 2,
        area: '9x13',
      },
    },

    {
      id: '16',
      title: 'Alberto Castillo Q.',
      price: 4000,
      img: office02,
      location: 'London, UK',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 2,
        area: '9x18',
      },
    },

    {
      id: '17',
      title: 'Laverde Vally',
      price: 2500,
      img: house02,
      location: 'London, UK',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 2,
        area: '9x15',
      },
    },

    {
      id: '18',
      title: 'Lissete Laverde',
      price: 4000,
      img: house03,
      location: 'Peru',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 2,
        area: '9x15',
      },
    },

    {
      id: '19',
      title: 'Laverde Avenue',
      price: 3500,
      img: house01,
      location: 'London, UK',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 2,
        area: '9x15',
      },
    },
    {
      id: '20',
      title: 'Go to Joss Woodhead',
      price: 3000,
      img: house02,
      location: 'Peru',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 2,
        area: '9x15',
      },
    },

    {
      id: '21',
      title: 'Go to Avi Werde',
      price: 2000,
      img: house01,
      location: 'Romania',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 2,
        area: '9x14',
      },
    },

    {
      id: '22',
      title: 'Go to Ronnie George',
      price: 2900,
      img: house02,
      location: 'California, USA',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 2,
        area: '9x14',
      },
    },

    {
      id: '23',
      title: 'Bailey Anselme',
      price: 4500,
      img: house01,
      location: 'Chicago, USA',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 2,
        area: '9x12',
      },
    },

    {
      id: '24',
      title: 'Go to Sora Sagano',
      price: 4500,
      img: office02,
      location: 'Romania',
      popular: true,
      date: '2022-02-03',
      propertyType: {
        name: 'Workspace',
        rooms: 4,
        bathrooms: 2,
        area: '9x12',
      },
    },

    {
      id: '25',
      title: 'Lighthouse',
      price: 4500,
      img: house02,
      location: 'London ,UK',
      popular: true,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 2,
        area: '9x12',
      },
    },

    {
      id: '26',
      title: 'Regan Ltd.',
      price: 4500,
      img: office02,
      location: 'Peru',
      popular: true,
      date: '2022-05-02',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 2,
        area: '9x12',
      },
    },

    {
      id: '27',
      title: 'Tom Valley',
      price: 4200,
      img: house01,
      location: 'Peru',
      popular: true,
      date: '2022-05-02',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 2,
        area: '9x15',
      },
    },

    {
      id: '28',
      title: 'Jerry Valley',
      price: 2500,
      img: house04,
      location: 'Peru',
      popular: true,
      date: '2022-01-10',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 2,
        area: '9x18',
      },
    },

    {
      id: '29',
      title: 'Harks Burk',
      price: 2500,
      img: office01,
      location: 'Peru',
      popular: true,
      date: '2022-02-03',
      propertyType: {
        name: 'Workspace',
        rooms: 4,
        bathrooms: 3,
        area: '9x15',
      },
    },

    {
      id: '30',
      title: 'Decan Throds',
      price: 3500,
      img: office02,
      location: 'Peru',
      popular: true,
      date: '2022-02-03',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 3,
        area: '9x15',
      },
    },

    {
      id: '31',
      title: 'Sillicon Ltd.',
      price: 5000,
      img: office03,
      location: 'Peru',
      popular: true,
      date: '2022-02-03',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 3,
        area: '9x15',
      },
    },

    {
      id: '32',
      title: 'Grameen Fds.',
      price: 3000,
      img: house01,
      location: 'Peru',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 3,
        area: '9x15',
      },
    },

    {
      id: '33',
      title: 'Greenwood Lodge',
      price: 4000,
      img: house01,
      location: 'Romania',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 3,
        area: '9x15',
      },
    },

    {
      id: '34',
      title: 'Tinkerface Lodge',
      price: 4500,
      location: 'Romania',
      popular: false,
      img: house01,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 3,
        area: '9x15',
      },
    },

    {
      id: '35',
      title: 'Robin Hood Ltd.',
      price: 4500,
      img: office03,
      location: 'Romania',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'Workspace',
        rooms: 4,
        bathrooms: 3,
        area: '9x14',
      },
    },

    {
      id: '36',
      title: 'John Signal Ltd.',
      price: 2500,
      img: office02,
      location: 'CA, USA',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'Workspace',
        rooms: 4,
        bathrooms: 3,
        area: '9x14',
      },
    },

    {
      id: '37',
      title: 'Signal House Ltd.',
      price: 2000,
      img: house03,
      location: 'Romania',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 3,
        area: '9x12',
      },
    },

    {
      id: '38',
      title: 'Signal House Ltd.',
      price: 4500,
      img: house01,
      location: 'Manchester, UK',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 3,
        area: '9x15',
      },
    },

    {
      id: '39',
      title: 'Wagon Rocks',
      price: 4500,
      img: office01,
      location: 'Manchester, UK',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 3,
        area: '9x12',
      },
    },

    {
      id: '40',
      title: 'Royal Cloud',
      price: 4200,
      img: office01,
      location: 'Manchester, UK',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 3,
        area: '9x12',
      },
    },

    {
      id: '41',
      title: 'Regal House',
      price: 4500,
      img: house04,
      location: 'UK',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 3,
        area: '9x12',
      },
    },

    {
      id: '42',
      title: 'Quebee',
      price: 3500,
      img: office02,
      location: 'Peru',
      popular: true,
      date: '2022-01-10',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 3,
        area: '9x12',
      },
    },

    {
      id: '43',
      title: 'Rej Tua',
      price: 4000,
      img: office01,
      location: 'Virginia, USA',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 3,
        area: '9x15',
      },
    },

    {
      id: '44',
      title: 'Ubia Tu',
      price: 3200,
      img: house02,
      location: 'Birmingham, UK',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 3,
        area: '9x15',
      },
    },

    {
      id: '45',
      title: 'Valor Row',
      price: 3000,
      img: office03,
      location: 'Birmingham, UK',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'Workspace',
        rooms: 4,
        bathrooms: 3,
        area: '9x15',
      },
    },

    {
      id: '46',
      title: 'Ruby House',
      price: 2200,
      img: house01,
      location: 'South Carolina, USA',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 3,
        area: '9x15',
      },
    },

    {
      id: '47',
      title: 'Ruby House',
      price: 2400,
      img: house02,
      location: 'London, UK',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 3,
        area: '9x15',
      },
    },

    {
      id: '48',
      title: 'Russ Fuss',
      price: 4000,
      img: office01,
      location: 'Washington DC, USA',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'Workspace',
        rooms: 4,
        bathrooms: 3,
        area: '9x15',
      },
    },

    {
      id: '49',
      title: 'Deloy Homes Ltd.',
      price: 4200,
      img: house02,
      location: 'Las Vegas, USA',
      popular: true,
      date: '2022-05-02',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 3,
        area: '9x16',
      },
    },

    {
      id: '50',
      title: 'Roma Toga',
      price: 3500,
      img: office02,
      location: 'Lasi, Romania',
      popular: true,
      date: '2022-01-10',
      propertyType: {
        name: 'Workspace',
        rooms: 4,
        bathrooms: 3,
        area: '9x14',
      },
    },

    {
      id: '51',
      title: 'Iconic Ltd.',
      price: 3000,
      img: office03,
      location: 'Sibiu, Romania',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'Workspace',
        rooms: 4,
        bathrooms: 3,
        area: '9x14',
      },
    },

    {
      id: '52',
      title: 'RRR House',
      price: 2500,
      img: house04,
      location: 'Romania',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'House',
        rooms: 2,
        bathrooms: 1,
        area: '9x12',
      },
    },

    {
      id: '53',
      title: 'Thu Rex',
      price: 4000,
      img: office01,
      location: 'Oradea, Romania',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 2,
        area: '9x15',
      },
    },

    {
      id: '54',
      title: 'Feda Co.',
      price: 3000,
      img: office01,
      location: 'Romania',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 2,
        area: '9x15',
      },
    },

    {
      id: '55',
      title: 'Happy House',
      price: 4200,
      img: house01,
      location: 'TX, USA',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 4,
        bathrooms: 2,
        area: '9x17',
      },
    },

    {
      id: '56',
      title: 'Ronald Kt.',
      price: 3000,
      img: office01,
      location: 'Peru',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'Workspace',
        rooms: 4,
        bathrooms: 3,
        area: '9x13',
      },
    },

    {
      id: '57',
      title: 'Paul Garden',
      price: 3000,
      img: house03,
      location: 'London, UK',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 3,
        area: '9x13',
      },
    },

    {
      id: '58',
      title: 'Akasha T',
      price: 4000,
      img: office03,
      location: 'Manchester, UK',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 2,
        area: '9x13',
      },
    },

    {
      id: '59',
      title: 'Hark House',
      price: 4200,
      img: house02,
      location: 'Romania',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 2,
        area: '9x16',
      },
    },

    {
      id: '60',
      title: 'Rose Garden',
      price: 3800,
      img: house04,
      location: 'London, UK',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 2,
        area: '9x15',
      },
    },

    {
      id: '61',
      title: 'Victoria Vally',
      price: 3000,
      img: office03,
      location: 'North Carolina, USA',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 3,
        area: '9x15',
      },
    },

    {
      id: '62',
      title: 'Deka Dukes',
      price: 4000,
      img: house03,
      location: 'Constanta, Romania',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 2,
        area: '9x13',
      },
    },

    {
      id: '63',
      title: 'Hamlock Ships',
      price: 2500,
      img: office01,
      location: 'Arad, Romania',
      popular: false,
      date: '2022-05-02',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 2,
        area: '9x13',
      },
    },

    {
      id: '64',
      title: 'Qa Osaka',
      price: 2600,
      img: office01,
      location: 'UK',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 3,
        area: '9x18',
      },
    },

    {
      id: '65',
      title: 'Tox Avenue',
      price: 2800,
      img: house02,
      location: 'Los Angeles, USA',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 2,
        area: '9x15',
      },
    },

    {
      id: '66',
      title: 'Ribbions Ltc',
      price: 4200,
      img: office02,
      location: 'Los Angeles, USA',
      popular: false,
      date: '2022-02-03',
      propertyType: {
        name: 'Workspace',
        rooms: 5,
        bathrooms: 3,
        area: '9x18',
      },
    },

    {
      id: '67',
      title: 'Thunder Snow',
      price: 2900,
      img: office02,
      location: 'Liverpool, UK',
      popular: false,
      date: '2022-01-10',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 2,
        area: '9x15',
      },
    },

    {
      id: '68',
      title: 'Nakota House',
      price: 2500,
      img: house02,
      location: 'Cardiff, UK',
      popular: true,
      date: '2022-01-10',
      propertyType: {
        name: 'House',
        rooms: 3,
        bathrooms: 2,
        area: '9x14',
      },
    },

    {
      id: '69',
      title: 'Hut Ed',
      price: 2500,
      img: office01,
      location: 'Peru',
      popular: true,
      date: '2022-01-10',
      propertyType: {
        name: 'Workspace',
        rooms: 3,
        bathrooms: 3,
        area: '9x14',
      },
    },
  ];
};

export default properties;
